version: 2.1
# obrs - reusable packages for application
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/docker@2.0.0
# jobs - set of intstructions / functions
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "installing dependencies...."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests....."
          npm run test
  publish: #also known as the build and push
    executor: docker/docker #define the execution environment in which the steps of a job will run
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: #build the image
          image: henryeff/education-space
          tag: v1.1.0
      - docker/push: #push the image to the specified account in the environment variables
          image: henryeff/education-space
          tag: v1.1.0

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          commands: |
            heroku container:login
            heroku container:push web -a hendry-su-devops
            heroku container:release web -a hendry-su-devops
#Workflow - defines what sequence will the jobs run
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish
