version: 2.1
# obrs - reusable packages for application
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
# jobs - set of intstructions / functions
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "installing dependencies...."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests....."
          npm run test
  publish: #also known as the build and push
    executor: docker/docker #define the execution environment in which the steps of a job will run
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: #build the image
          image: henryeff/education-space
      - docker/push: #push the image to the specified account in the environment variables
          image: henryeff/education-space
#Workflow - defines what sequence will the jobs run
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
