version: 2.1
# obrs - reusable packages for application
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  #  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0 #compare the node and docker orbs, the snyk orbs with snyk and it's considered a third party orb
# jobs - set of intstructions / functions
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "installing dependencies...."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests....."
          npm run test
  publish: #also known as the build and push
    executor: docker/docker #define the execution environment in which the steps of a job will run
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: #build the image
          image: henryeff/education-space
          tag: v1.1.1
      - docker/push: #push the image to the specified account in the environment variables
          image: henryeff/education-space
          tag: v1.1.1

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku container:push web -a hendry-su-devops
            heroku container:release web -a hendry-su-devops

  scan:
    docker:
      - image: cimg/node:16:10
    environment: #environment allow us to create an environment for the job and allows us to create custom environment varibales
      IMAGE_NAME: henryeff/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME . #$IMAGE_NAME gets the value from the environment we created above
      - snyk/scan:
          docker-image-name: $IMAGE_NAME

#Workflow - defines what sequence will the jobs run
workflows:
  simple_workflow:
    jobs:
      - build:
          #additional filters
          filters:
            branches:
              only: main #build job would only run when code changes are pushed to the main branch
      - test:
          requires:
            - build
          filters:
            branches:
              only: main
      - scan:
          requres:
            - build
          filters:
            branches:
              only: main
#      - publish:
#          requires:
#            - test
#      - deploy:
#          requires:
#            - publish
